### ISSUE TITLE
Sample Project for Model Transformation

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#336]
# Feature Request 🛍️
Provide a sample repo to illustrate model transformation using e.g. the Typescript transform to generate front-end code and the Java or C# transform to generate backend code, publishing the code to module repositories for use in downstream modules.

**Comment by apoorvsxna** [comment]
Hi @dselman . Could you please elaborate the requirements of the issue?

I understand that a new repository is to be created, containing sample concerto models and their transformed code, for frontend and backend languages, in order to demonstrate the usage of concerto and for direct usage in other modules without having to redefine models. Am I right?

Also, which models in particular are supposed to be included in the repository?
